# Project-wide Gradle settings

# JVM memory for Gradle Daemon
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Android-specific settings
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin settings
kotlin.code.style=official

# Enable Gradle configuration cache
org.gradle.configuration-cache=true
